
name: Gitlab Stats update
on:

  schedule:
    - cron: "0 0 * * *"
  # push
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout ${{ github.event.repository.name }} repository
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Checkout gitlab-stats repository
        uses: actions/checkout@v2
        with:
          repository: 'emochka2007/gitlab-stats'
          token: ${{ secrets.GITHUB_TOKEN }}   # Use a GitHub Secret for the token
          path: 'gitlab_stats'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build and run Rust application
        run: cargo run ${{ secrets.GITLAB_USERNAME }} > ../${{ github.event.repository.name }}/output.md
        working-directory: gitlab_stats

      - name: Update README
        run: |
            sed -i '/^<!--START_SECTION:emo-gitlab-->$/,/^<!--END_SECTION:emo-gitlab-->/{//!d;}' README.md
            sed -i '/^<!--START_SECTION:emo-gitlab-->/r ./output.md' README.md
        working-directory: ${{ github.event.repository.name }}

      - name: Commit and push changes
        run: |
            git config --global user.name ${{ github.actor }}
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
            git add README.md
            git commit -m "Updated README with new stats"
            git push
        working-directory: ${{ github.event.repository.name }}